export const LISTA_CICLOS = 'LISTA_CICLOS';
export const LIMPIAR_LISTA_CICLOS = 'LIMPIAR_LISTA_CICLOS';
export const LISTA_APLICACIONES = 'LISTA_APLICACIONES';

/* export const OBJETO_CLIENTE= 'OBJETO_CLIENTE';
export const CLEAR_OBJETO_CLIENTE= 'CLEAR_OBJETO_CLIENTE';
export const BUSQUEDA_NOMBRE_CLIENTE= 'BUSQUEDA_NOMBRE_CLIENTE';
export const LISTA_PAISES= 'LISTA_PAISES';
export const LISTA_CIUDADES= 'LISTA_CIUDADES';
export const LISTA_BAJAS= 'LISTA_BAJAS';
export const LISTA_BANCOS= 'LISTA_BANCOS';

export const UPDATE_CLIENTE= 'UPDATE_CLIENTE'; */