export const LISTA_AREAS= 'LISTA_AREAS';
export const LISTA_SUCURSALES= 'LISTA_SUCURSALES';
export const LISTA_PAGINAS= 'LISTA_PAGINAS';
export const LISTA_PERMISOS= 'LISTA_PERMISOS';
export const LISTA_GLOBAL_ROLES_MODULOS= 'LISTA_GLOBAL_ROLES_MODULOS';
export const LISTA_GLOBAL_ROLES_MODULOS_VACIAR = 'LISTA_GLOBAL_ROLES_MODULOS_VACIAR';
export const OBJETO_GLOBAL_ROLES_MODULOS= 'OBJETO_GLOBAL_ROLES_MODULOS';
export const OBJETO_GLOBAL_ROLES_MODULOS_VACIO= 'OBJETO_GLOBAL_ROLES_MODULOS_VACIO';